//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDCapAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Partcipation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Partcipation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REDCapAPI.Partcipation", typeof(Partcipation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestCode.
        /// </summary>
        internal static string _667469 {
            get {
                return ResourceManager.GetString("667469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExposureSite.
        /// </summary>
        internal static string CON106 {
            get {
                return ResourceManager.GetString("CON106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvestgrOfConRec.
        /// </summary>
        internal static string CON137 {
            get {
                return ResourceManager.GetString("CON137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OthInfPatOfConRec.
        /// </summary>
        internal static string CON142 {
            get {
                return ResourceManager.GetString("CON142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispoInvestgrOfConRec.
        /// </summary>
        internal static string CON147 {
            get {
                return ResourceManager.GetString("CON147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerAsProviderOfDelivery.
        /// </summary>
        internal static string CS007 {
            get {
                return ResourceManager.GetString("CS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerAsProvideroOfPediatrics.
        /// </summary>
        internal static string CS008 {
            get {
                return ResourceManager.GetString("CS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgAsHospitalOfDelivery.
        /// </summary>
        internal static string CS009 {
            get {
                return ResourceManager.GetString("CS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerAsCaseReviewer.
        /// </summary>
        internal static string CS013 {
            get {
                return ResourceManager.GetString("CS013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerAsProviderOfOBGYN.
        /// </summary>
        internal static string CS182 {
            get {
                return ResourceManager.GetString("CS182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvestgrOfPHC.
        /// </summary>
        internal static string INV180 {
            get {
                return ResourceManager.GetString("INV180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerAsReporterOfPHC.
        /// </summary>
        internal static string INV181 {
            get {
                return ResourceManager.GetString("INV181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicianOfPHC.
        /// </summary>
        internal static string INV182 {
            get {
                return ResourceManager.GetString("INV182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgAsReporterOfPHC.
        /// </summary>
        internal static string INV183 {
            get {
                return ResourceManager.GetString("INV183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HospOfADT.
        /// </summary>
        internal static string INV184 {
            get {
                return ResourceManager.GetString("INV184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntrvwerOfInterview.
        /// </summary>
        internal static string IXS102 {
            get {
                return ResourceManager.GetString("IXS102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntrvweeOfInterview.
        /// </summary>
        internal static string IXS104 {
            get {
                return ResourceManager.GetString("IXS104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitFupInvestgrOfPHC.
        /// </summary>
        internal static string NBS139 {
            get {
                return ResourceManager.GetString("NBS139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurvInvestgrOfPHC.
        /// </summary>
        internal static string NBS145 {
            get {
                return ResourceManager.GetString("NBS145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FldFupInvestgrOfPHC.
        /// </summary>
        internal static string NBS161 {
            get {
                return ResourceManager.GetString("NBS161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitFldFupInvestgrOfPHC.
        /// </summary>
        internal static string NBS163 {
            get {
                return ResourceManager.GetString("NBS163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FldFupProvOfPHC.
        /// </summary>
        internal static string NBS171 {
            get {
                return ResourceManager.GetString("NBS171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FldFupFacilityOfPHC.
        /// </summary>
        internal static string NBS172 {
            get {
                return ResourceManager.GetString("NBS172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispoFldFupInvestgrOfPHC.
        /// </summary>
        internal static string NBS175 {
            get {
                return ResourceManager.GetString("NBS175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FldFupSupervisorOfPHC.
        /// </summary>
        internal static string NBS176 {
            get {
                return ResourceManager.GetString("NBS176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterviewerOfPHC.
        /// </summary>
        internal static string NBS186 {
            get {
                return ResourceManager.GetString("NBS186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitInterviewerOfPHC.
        /// </summary>
        internal static string NBS188 {
            get {
                return ResourceManager.GetString("NBS188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASupervisorOfPHC.
        /// </summary>
        internal static string NBS190 {
            get {
                return ResourceManager.GetString("NBS190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosureInvestgrOfPHC.
        /// </summary>
        internal static string NBS197 {
            get {
                return ResourceManager.GetString("NBS197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceAsHangoutOfPHC.
        /// </summary>
        internal static string NBS243 {
            get {
                return ResourceManager.GetString("NBS243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceAsSexOfPHC.
        /// </summary>
        internal static string NBS290 {
            get {
                return ResourceManager.GetString("NBS290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgAsClinicOfPHC.
        /// </summary>
        internal static string NBS291 {
            get {
                return ResourceManager.GetString("NBS291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubOfVacc.
        /// </summary>
        internal static string NBS320 {
            get {
                return ResourceManager.GetString("NBS320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformerOfVacc.
        /// </summary>
        internal static string VAC116 {
            get {
                return ResourceManager.GetString("VAC116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformerOfVacc.
        /// </summary>
        internal static string VAC117 {
            get {
                return ResourceManager.GetString("VAC117", resourceCulture);
            }
        }
    }
}
